site_name: 'Binary Ninja Sidekick User Documentation'
copyright: '© Copyright 2015-2025, Vector 35 Inc'
theme:
  name: material
  favicon: 'images/favicon.ico'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: red
    accent: grey
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: red
    accent: blue grey
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  highlightjs: false
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 191  # ? / /
nav:
  - Home: 'index.md'
  - 'getting-started.md'
  - User's Guide:
    - Introduction: guide/intro.md
    - Deep Analysis:
      - Analysis Console: guide/analysis/analysis_console.md
      - Analysis Indexes: guide/analysis/analysis_indexes.md
      - Code Insight Map: guide/analysis/code_insight_map.md
    - Smart Automation:
      - Automation Workbench: guide/automation/automation_workbench.md
    - Improved Decompilation:
      - Decompilation Suggestions: guide/decompilation/suggestions.md
      - Structure Recovery: guide/decompilation/structures.md
      - Naming: guide/decompilation/naming.md
      - Comments: guide/decompilation/comments.md
    - Artifacts:
      - Documentation: guide/artifacts/documentation.md
    - Management:
      - Change Log: guide/management/change_log.md
  - "Known Issues":
    - SKI-1: issues/ski-1.md
    - SKI-2: issues/ski-2.md
  - Reference:
    - Binary Ninja Query Language: guide/analysis/bnql.md
  - About:
    - Sidekick: 'about/about.md'
    - Legal Terms and Conditions: 'about/legal-terms-and-conditions.md'
    - Open Source: 'about/open-source.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: True
extra_css:
  - docs.css

extra:
  version:
    provider: mike
    alias: true
    default: latest
